api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from .views import (
    HydroponicSystemListAPIView,
    HydroponicSystemRetrieveUpdateDestroyAPIView,
    MeasurementCreateAPIView,
    MeasurementListAPIView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Hydroponics",
        default_version="v1",
        description="Interview",
        contact=openapi.Contact(email="mateuszrosenkranz@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

app_name = "api"

urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("", MeasurementCreateAPIView.as_view(), name="send-measurement"),
    path(
        "hydroponics/",
        include(
            [
                path("", HydroponicSystemListAPIView.as_view(), name="list"),
                path(
                    "<int:pk>/",
                    HydroponicSystemRetrieveUpdateDestroyAPIView.as_view(),
                    name="rud-hydroponic-system",
                ),
            ]
        ),
    ),
    path(
        "measurements/<int:pk>/",
        MeasurementListAPIView.as_view(),
        name="measurement-list",
    ),
]

hydroponics/urls.py
from django.contrib import admin
from django.urls import include, path

from .env import env

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("", include("hydroponics_manager.urls")),
]

# if env("DEBUG"):
#     urlpatterns += [
#         path("silk/", include("silk.urls", namespace="silk")),
#         path("__debug__/", include("debug_toolbar.urls")),
#
#     ]

hydroponics_manager/urls.py
from django.contrib.auth.views import LoginView
from django.urls import include, path

from .views import (
    CustomLogoutView,
    HydroponicSystemCreateView,
    HydroponicSystemDeleteView,
    HydroponicSystemDetailView,
    HydroponicSystemListView,
    HydroponicSystemUpdateView,
    SignUpView,
)

app_name = "hydroponic_system"

urlpatterns = [
    path("", HydroponicSystemListView.as_view(), name="list"),
    path(
        "login/",
        LoginView.as_view(template_name="hydroponics_manager/login.html"),
        name="login",
    ),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("create/", HydroponicSystemCreateView.as_view(), name="create"),
    path(
        "hydroponicsystem/<int:pk>/",
        include(
            [
                path("", HydroponicSystemDetailView.as_view(), name="detail"),
                path("update/", HydroponicSystemUpdateView.as_view(), name="update"),
                path("delete/", HydroponicSystemDeleteView.as_view(), name="delete"),
            ]
        ),
    ),
]

hydroponics_manager/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import QuerySet


class HydroponicsType(models.TextChoices):
    # https://www.wiki.haszysz.com/index.php/Rodzaje_system%C3%B3w_hydroponicznych
    AEROPONIC = "AEROPONIC", "Aeroponic Systems"
    DRIPPER_FEED = "DRIPPER_FEED", "Dripper Feed Systems"
    EBB_AND_FLOOD = "EBB_AND_FLOOD", "Ebb & Flood System"
    NFT = "NFT", "Nutrient Film Technique"
    POT = "POT", "POT CULTURE"


class HydroponicSystem(models.Model):
    """
    Model presents hydroponic system
    """

    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="systems")

    name = models.CharField(max_length=150)
    description = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    system_type = models.CharField(
        max_length=50,
        choices=HydroponicsType.choices,
        help_text="Type of hydroponic system",
    )

    created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    water_capacity = models.FloatField(blank=True, null=True)

    # I could add fields for example: water_refill_interval, nutrient_refill_interval, pump_runtime_daily
    class Meta:
        ordering = ("-created",)
        # unique_together = ("owner", "name")

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("hydroponic_system:detail", kwargs={"pk": self.pk})

    def last_measurements(self) -> QuerySet:
        return self.measurements.all().values(
            "timestamp", "ph", "water_temperature", "tds"
        )[:10]


class Measurement(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    ph = models.FloatField(
        blank=True,
        null=True,
        validators=[MinValueValidator(0.0), MaxValueValidator(14.0)],
    )
    water_temperature = models.FloatField(
        blank=True,
        null=True,
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],
        help_text="Water temperature is measured in degrees Celsius",
    )
    tds = models.FloatField(
        blank=True, null=True, help_text="TDS is present in mg/L units"
    )
    hydroponic_system = models.ForeignKey(
        HydroponicSystem, on_delete=models.CASCADE, related_name="measurements"
    )

    class Meta:
        ordering = ["-timestamp"]

    def save(self, *args, **kwargs) -> None:
        if self.ph and not (0 <= self.ph <= 14):
            raise ValidationError({"ph": "pH value must be between 0 and 14"})

        if self.water_temperature and not (0 <= self.water_temperature <= 100):
            raise ValidationError(
                {"water_temperature": "The water temperature must be between 0 and 100"}
            )

        super(Measurement, self).save()

hydroponics_manager/forms.py
from typing import Any

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import HydroponicSystem


class HydroponicSystemForm(forms.ModelForm):
    class Meta:
        model = HydroponicSystem
        fields = ("name", "description", "system_type", "water_capacity")


class CustomCreateUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_email(self) -> Any | None:
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists!")
        return email

hydroponics_manager/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
    View,
)

from .forms import CustomCreateUserForm, HydroponicSystemForm
from .models import HydroponicSystem


class SignUpView(SuccessMessageMixin, CreateView):
    model = User
    form_class = CustomCreateUserForm
    template_name = "hydroponics_manager/form.html"
    extra_context = {"button_name": "Sign Up"}
    success_url = reverse_lazy("hydroponic_system:login")
    success_message = "User was created successfully"


class CustomLogoutView(View):
    def get(
        self, request, *args, **kwargs
    ) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
        logout(request)
        return redirect("hydroponic_system:login")


# CRUD HydroponicSystem Views
class HydroponicSystemCreateView(LoginRequiredMixin, CreateView):
    model = HydroponicSystem
    template_name = "hydroponics_manager/form.html"
    form_class = HydroponicSystemForm
    extra_context = {"button_name": "Create"}

    def form_valid(self, form) -> HttpResponseRedirect:
        instance = form.save(commit=False)
        instance.owner = self.request.user
        instance.save()
        return super(HydroponicSystemCreateView, self).form_valid(form)


class CustomPassesTestMixin(UserPassesTestMixin):
    def test_func(self) -> bool:
        return HydroponicSystem.objects.filter(
            owner=self.request.user, pk=self.kwargs.get("pk")
        ).exists()


class HydroponicSystemDetailView(LoginRequiredMixin, CustomPassesTestMixin, DetailView):
    model = HydroponicSystem
    template_name = "hydroponics_manager/detail.html"


class HydroponicSystemUpdateView(LoginRequiredMixin, CustomPassesTestMixin, UpdateView):
    model = HydroponicSystem
    template_name = "hydroponics_manager/form.html"
    form_class = HydroponicSystemForm
    extra_context = {"button_name": "Update"}


class HydroponicSystemDeleteView(LoginRequiredMixin, CustomPassesTestMixin, DeleteView):
    model = HydroponicSystem
    template_name = "hydroponics_manager/delete_confirm.html"
    success_url = reverse_lazy("hydroponic_system:list")


class HydroponicSystemListView(LoginRequiredMixin, ListView):
    model = HydroponicSystem
    template_name = "hydroponics_manager/list.html"

    def get_queryset(self) -> QuerySet:
        return HydroponicSystem.objects.filter(owner=self.request.user).values(
            "pk", "name"
        )

hydroponics_manager/templates/hydroponics_manager/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
            {% block title %}{% endblock %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">
    </head>
    <body>
        <ul class="nav justify-content-center">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active"
                       aria-current="page"
                       href="{% url 'hydroponic_system:list' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'hydroponic_system:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'hydroponic_system:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'hydroponic_system:signup' %}">Sign up</a>
                </li>
            {% endif %}
        </ul>
        {% if messages %}
            {% for message in messages %}<div class="alert alert-{{ message.tags }}">{{ message }}</div>{% endfor %}
        {% endif %}
        <div class="container text-center my-3">
            {% block content %}{% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
                integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
                integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
                crossorigin="anonymous"></script>
    </body>
</html>

hydroponics_manager/templates/hydroponics_manager/delete_confirm.html
{% extends "hydroponics_manager/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Delete{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-5 m-5">
            <h1>Do you want delete object: {{ object.name }}</h1>
            <form method="post">
                {% csrf_token %}
                <a class="btn btn-success my-2 "
                   href="{% url 'hydroponic_system:detail' object.pk %}">No</a>
                <button type="submit" class="btn btn-danger my-2">Yes</button>
            </form>
        </div>
    </div>
{% endblock %}

hydroponics_manager/templates/hydroponics_manager/detail.html
{% extends "hydroponics_manager/base.html" %}
{% block title %}{{ object.name }}{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-5 mt-5 mb-3">
            <h1>{{ object.name }}</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-5">
                <div class="row">
                    <div class="col-6">
                        <b>Name</b>
                    </div>
                    <div class="col-6 text-start">{{ object.name }}</div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <b>Description</b>
                    </div>
                    <div class="col-6 text-start">{{ object.description }}</div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <b>Location</b>
                    </div>
                    <div class="col-6 text-start">{{ object.location }}</div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <b>System Type</b>
                    </div>
                    <div class="col-6 text-start">{{ object.get_system_type_display }}</div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <b>Created</b>
                    </div>
                    <div class="col-6 text-start">{{ object.created }}</div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <b>PK</b>
                    </div>
                    <div class="col-6 text-start">{{ object.pk }}</div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <b>Active</b>
                    </div>
                    <div class="col-6 text-start">{{ object.is_active }}</div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <b>Water capacity</b>
                    </div>
                    <div class="col-6 text-start">{{ object.water_capacity }}</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-5 m-2">
            <a class="btn btn-primary my-2"
               href="{% url 'hydroponic_system:update' object.pk %}">Update</a>
            <a class="btn btn-primary my-2"
               href="{% url 'hydroponic_system:delete' object.pk %}">Delete</a>
        </div>
    </div>
    <div class="row justify-content-center my-3">
        <h1>Last measurements:</h1>
        {% for m in object.last_measurements %}
            <div class="col-2 m-2">
                {{ m.timestamp|date:"d M Y" }}
                <ul class="list-group">
                    <li class="list-group-item">pH: {{ m.ph }}</li>
                    <li class="list-group-item">Water Temperature: {{ m.water_temperature }}</li>
                    <li class="list-group-item">TDS: {{ m.tds }}</li>
                </ul>
            </div>
        {% endfor %}
    </div>
{% endblock %}

hydroponics_manager/templates/hydroponics_manager/form.html
{% extends "hydroponics_manager/base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ button_name }}{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-5 m-5">
            <h1>{{ button_name }} section</h1>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary my-2" type="submit">{{ button_name }}</button>
            </form>
        </div>
    </div>
{% endblock %}

hydroponics_manager/templates/hydroponics_manager/list.html
{% extends "hydroponics_manager/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-5 mt-5 mb-3">
            <h1>Your Hydroponic systems</h1>
            <a href="{% url 'hydroponic_system:create' %}"
               class="btn btn-primary my-2">Add</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-5 ">
            <div class="list-group">
                {% for system in object_list %}
                    <a href="{% url 'hydroponic_system:detail' system.pk %}"
                       class="list-group-item list-group-item-action">{{ system.name }}</a>
                {% empty %}
                    <h3>You don't have any systems!</h3>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

hydroponics_manager/templates/hydroponics_manager/login.html
{% extends "hydroponics_manager/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-5 m-5">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary my-2" type="submit">Login</button>
            </form>
        </div>
    </div>
{% endblock %}